name: "🐞 Bug Report"
description: Report a reproducible bug in Kuso Physics
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill in the details below.
  - type: input
    id: environment
    attributes:
      label: Environment
      description: What platform are you using?
      placeholder: e.g., Chrome 123 on macOS, iPhone 14
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the bug?
      placeholder: |
        1. Go to level editor
        2. Place a platform and run
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
  - type: textarea
    id: logs
    attributes:
      label: Screenshots / Console Logs
      description: Include screenshots or error messages if applicable
