name: "✨ Feature Request"
description: Suggest a new idea for Kuso Physics
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping make Kuso Physics better! Please tell us about your idea.
  - type: textarea
    id: proposal
    attributes:
      label: Feature Description
      description: What do you want to add or change?
      placeholder: |
        I'd like a way to...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why Is This Useful?
      description: Tell us why this feature would improve the game.
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What area does this affect?
      options:
        - Core gameplay
        - Level editor
        - UI/UX
        - Educational content
        - Other
